name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests 
        run: go test ./internal/persons-service/...


  build:
    name: Build Docker image
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU for Docker build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/persons-service/Dockerfile
          push: true
          tags: erlendum/rsoi-lab-01:latest
          build-args: |
            PIPELINE_ID=${{ github.run_number }}
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        env:
          EXT_PORT: ${{ secrets.PERSONS_SERVICE_EXT_PORT }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          envs: EXT_PORT
          allenvs: true
          script: >-
            docker pull erlendum/rsoi-lab-01:latest &&
            (docker stop persons-service && docker rm persons-service || true) &&
            docker run --env-file /envs/persons-service.env --name persons-service -p $EXT_PORT:8018 --restart always -d erlendum/rsoi-lab-01
